title: Personal Blog of David Debeljak
description: Some of my thoughts on technology and learning
author: David Debeljak

theme: minima

# Make it very minimal and clean (close to Vitalik style)
minima:
  skin: dark
  date_format: "%Y-%m-%d"

# Show full posts on the front page
show_excerpts: false